name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # ou a branch em que você deseja atualizar o GitHub Pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: npm install
      - name: Build site
        run: npm run build # ou o comando para construir o seu site
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./pokedex # ou o diretório em que o seu site foi construído
